### ISSUE TITLE
【TheBridge】血量 & 擊殺 Problem #2個問題

### ISSUE THREAD

**Issue by Zhuyuan0907** [RealGoodestEnglish/Eden#11]
https://www.youtube.com/watch?v=qhMlySGK7bc&ab_channel=%E5%A4%A9%E7%A5%9EZhuyuan
上面這部 是關於血量
主要是在遊玩TheBridge時
我們兩個都剩下一點點血量
然後有一方跳進去洞裡
照理來講血量會回滿
但血量不會回滿

https://www.youtube.com/watch?v=oD6k0rrNVTk&ab_channel=%E5%A4%A9%E7%A5%9EZhuyuan
下面這部呢 是關於擊殺
不管我有沒有打到對方
對方只要掉入虛空裡
就會判斷是對手擊殺的!

**Comment by RealGoodestEnglish** [comment]
已修復 - https://github.com/RealGoodestEnglish/Eden/releases/tag/1.0.11-BETA-3d1abd2
