### ISSUE TITLE
Compiling issues

### ISSUE THREAD

**Issue by AnxietyDev** [RealGoodestEnglish/Eden#12]
Hello, im having some issues compiling. it isnt sending the finish build to a file location, do you mind helping me fix this issue?

**Comment by RealGoodestEnglish** [comment]
Hello. Please send me the compiling error so I can know what causes the error. 
Also, we provide [jar file](https://github.com/RealGoodestEnglish/Eden/tags) to download so you don't have to compile it by yourself.

**Comment by AnxietyDev** [comment]
Ive manage to fix the compile issue by adding a path via build.gradle
