### ISSUE TITLE
Mongodb Issues.

### ISSUE THREAD

**Issue by AnxietyDev** [RealGoodestEnglish/Eden#13]
Im currently getting some MongoDB issues. I have my Db setup on other plugins, so i know my database works fine, may you check opn this issue? 

Error Code
https://pastebin.com/FCECLrTM

**Comment by RealGoodestEnglish** [comment]
Hello, what other plugins you are using which has mongodb connection?

**Comment by AnxietyDev** [comment]
I've noticed that using the jar via the release works fine, 
Release file size : 2.8 MB
File I compile : 678 KB
maybe I didn't compile it correctly or it's missing something.

May you instruct me on how to correctly compile so I can use my changes.

**Comment by RealGoodestEnglish** [comment]
Make sure you use shadowJar to compile instead, not the normal one.

**Comment by AnxietyDev** [comment]
okay, ive done that and im getting this error 

```
[23:15:11 ERROR]: Error occurred while enabling Eden v1.0.11-BETA- (Is it up to date?)
java.lang.IllegalArgumentException: The connection string contains an invalid host 'null:0'. The port '0' is not a valid, it must be an integer between 0 and 65535
        at com.mongodb.ConnectionString.validatePort(ConnectionString.java:1085) ~[?:?]
        at com.mongodb.ConnectionString.parseHosts(ConnectionString.java:1065) ~[?:?]
        at com.mongodb.ConnectionString.<init>(ConnectionString.java:359) ~[?:?]
        at com.mongodb.client.MongoClients.create(MongoClients.java:61) ~[?:?]
        at rip.diamond.practice.database.MongoManager.init(MongoManager.java:47) ~[?:?]
        at rip.diamond.practice.database.MongoManager.<init>(MongoManager.java:23) ~[?:?]
        at rip.diamond.practice.Eden.loadManagers(Eden.java:135) ~[?:?]
        at rip.diamond.practice.Eden.onEnable(Eden.java:106) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:334) ~[CarbonSpigot.jar:git-Carbon-7b3f7ad]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:323) ~[CarbonSpigot.jar:git-Carbon-7b3f7ad]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:395) ~[CarbonSpigot.jar:git-Carbon-7b3f7ad]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:369) ~[CarbonSpigot.jar:git-Carbon-7b3f7ad]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:328) ~[CarbonSpigot.jar:git-Carbon-7b3f7ad]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:367) ~[CarbonSpigot.jar:git-Carbon-7b3f7ad]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:331) ~[CarbonSpigot.jar:git-Carbon-7b3f7ad]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:285) ~[CarbonSpigot.jar:git-Carbon-7b3f7ad]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:307) ~[CarbonSpigot.jar:git-Carbon-7b3f7ad]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:526) ~[CarbonSpigot.jar:git-Carbon-7b3f7ad]
        at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_352]
```

**Comment by AnxietyDev** [comment]
**This is my Config**
```

## Developer option, set to false if GoodestEnglish didn't tell you to set to true
debug: false
## MongoDB login information
mongo:
  uri-mode: false
  normal:
    host: IP
    port: 27017
    auth:
      enabled: true
      username: 'admin'
      password: 'PASS'
  uri:
    database: Practice
    connection-string: mongodb://admin:PASS@IP:27017
fancy-tablist:
  ## Toggle if the fancy tablist should be enabled or not
  enabled: true
  ## How should each tab element shown
  ## This supports PlaceholderAPI, so if you wish to show player prefix, you can do it!
  format: "&a{player-name}"
  ## The ticks of how often the tablist will be updated
  ## Default is 20, which is 1 second. 1 tick is equal to 0.05 second
  update-ticks: 20
nametag:
  ## Toggle if the plugin should modify the nametag color or not
  enabled: true
  ## What color should the nametag be when the player is in lobby?
  ## Check https://hub.spigotmc.org/javadocs/spigot/org/bukkit/ChatColor.html for available colors
  color: BLUE
party:
  ## When player creates a party, what is the default size?
  default-max-size: 30
lobby:
  ## Should player allow to see other players?
  display-players: false
match:
  goal-portal-protect-radius: 3
  ## Right now boxing will count hit as 2 hits if player is spam clicking and jumping (critical hits)
  ## This option will change paperspigot's config 'disable-player-crits' to true. So crit hit will not be exists anymore.
  ## Warning: This option will disable crit damage, and will change and save paperspigot's 'disable-player-crits' settings
  fix-hit-count-error: true
## Simple chat format
chat-format:
  ## Set this to true if you want to enable chat format
  enabled: true
  ## What is the format should be? (This supports PlaceholderAPI)
  ## Use %1$s for player's name and %2$s for player's message
  format: "&a%1$s&f: %2$s"
## These options will only works if you are using ImanitySpigot
## If you are not using, then turn every imanity related settings off
imanity:
  teleport-async: true
```

**I removed my Information for security reasons!**

**Comment by Zhuyuan0907** [comment]
> **This is my Config**
> 
> ```
> 
> ## Developer option, set to false if GoodestEnglish didn't tell you to set to true
> debug: false
> ## MongoDB login information
> mongo:
>   uri-mode: false
>   normal:
>     host: IP
>     port: 27017
>     auth:
>       enabled: true
>       username: 'admin'
>       password: 'PASS'
>   uri:
>     database: Practice
>     connection-string: mongodb://admin:PASS@IP:27017
> fancy-tablist:
>   ## Toggle if the fancy tablist should be enabled or not
>   enabled: true
>   ## How should each tab element shown
>   ## This supports PlaceholderAPI, so if you wish to show player prefix, you can do it!
>   format: "&a{player-name}"
>   ## The ticks of how often the tablist will be updated
>   ## Default is 20, which is 1 second. 1 tick is equal to 0.05 second
>   update-ticks: 20
> nametag:
>   ## Toggle if the plugin should modify the nametag color or not
>   enabled: true
>   ## What color should the nametag be when the player is in lobby?
>   ## Check https://hub.spigotmc.org/javadocs/spigot/org/bukkit/ChatColor.html for available colors
>   color: BLUE
> party:
>   ## When player creates a party, what is the default size?
>   default-max-size: 30
> lobby:
>   ## Should player allow to see other players?
>   display-players: false
> match:
>   goal-portal-protect-radius: 3
>   ## Right now boxing will count hit as 2 hits if player is spam clicking and jumping (critical hits)
>   ## This option will change paperspigot's config 'disable-player-crits' to true. So crit hit will not be exists anymore.
>   ## Warning: This option will disable crit damage, and will change and save paperspigot's 'disable-player-crits' settings
>   fix-hit-count-error: true
> ## Simple chat format
> chat-format:
>   ## Set this to true if you want to enable chat format
>   enabled: true
>   ## What is the format should be? (This supports PlaceholderAPI)
>   ## Use %1$s for player's name and %2$s for player's message
>   format: "&a%1$s&f: %2$s"
> ## These options will only works if you are using ImanitySpigot
> ## If you are not using, then turn every imanity related settings off
> imanity:
>   teleport-async: true
> ```
> 
> **I removed my Information for security reasons!**

![image](https://user-images.githubusercontent.com/75146874/200794082-27f640d5-7713-493d-a8c6-52f00ea7352e.png)
uhh, wtf is your mongoDB
host is your mongoDB ip, not "IP"

**Comment by AnxietyDev** [comment]
I've already told you, I removed my ip & password for security purposes.

**Comment by RealGoodestEnglish** [comment]
I saw you asked about compiling issue. Did you change anything in the source code?

**Comment by AnxietyDev** [comment]
I manage to get the issue fixed, but now im running into another issue, just testing out the core.


https://user-images.githubusercontent.com/56962362/200916224-8fb9a2d4-2526-44b3-af42-cbfef3af3ea7.mp4

**Comment by AnxietyDev** [comment]
when the round starts and you move, it automatically eliminate the user who moves.

**Comment by RealGoodestEnglish** [comment]
Any error in console? The inventory looks like it is not cleared. I assume there's an error when starting the match.
Also, have you set the arena max/min position? When a player moved out from the box, they will be automatically eliminated.

**Comment by AnxietyDev** [comment]
arena max/min position has 
![image](https://user-images.githubusercontent.com/56962362/200918318-3afc5068-9a6a-4c28-862e-de494e0bfc30.png)

![image](https://user-images.githubusercontent.com/56962362/200918330-7b82fc12-b3dc-4074-934c-3923a964c2b2.png)

**Comment by AnxietyDev** [comment]
also, no theirs no errors, via console.

**Comment by RealGoodestEnglish** [comment]
May you please send me your arena.yml?

**Comment by AnxietyDev** [comment]
arenas:
  Stone:
    icon: |
      rO0ABXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFwdAAPTGph
      dmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFibGVNYXAk
      U2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmplY3Q7WwAG
      dmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAAAAJ0AAI9
      PXQABHR5cGV1cQB+AAYAAAACdAAeb3JnLmJ1a2tpdC5pbnZlbnRvcnkuSXRlbVN0YWNrdAAFR1JB
      U1M=
    y-limit: 256
    build-max: -1
    kits:
    - Nodebuff
    - NoDebuff
    enabled: true
    details:
      '0':
        a: '#w;world:#x;193.59324426224896:#y;83.3836770795054:#z;336.9418968352552:#p;-3.0655236:#yaw;-2.7313395'
        b: '#w;world:#x;195.09763812739735:#y;83.3836770795054:#z;380.58041099531323:#p;-0.5713741:#yaw;180.19328'
        min: '#w;world:#x;208.0:#y;80.0:#z;332.0:#p;0.0:#yaw;0.0'
        max: '#w;world:#x;178.0:#y;112.0:#z;386.0:#p;0.0:#yaw;0.0'

**Comment by RealGoodestEnglish** [comment]
My wiki might be misunderstanding for some people. Apologize for that.
The reason why you instant die is because the y-limit is 256, which is higher than your location.
According to [wiki](https://github.com/RealGoodestEnglish/Eden/wiki/Arenas-Setup#y-limit): `Player who is under this Y-Level will receive 99999 damage(Instant Death)`
In your case, the y-limit should be 81 since you are trying to build a normal arena.

**Comment by AnxietyDev** [comment]
Okay, thanks for explaining it.
