### ISSUE TITLE
Plugin not work

### ISSUE THREAD

**Issue by endrmen9487** [RealGoodestEnglish/Eden#14]
[新文字文件.txt](https://github.com/RealGoodestEnglish/Eden/files/10049273/default.txt)
我正在使用Feather Client的伺服器功能使用此插件，但是伺服器偵測不到Eden跟其他插件(WorldEdit
 FastAsyncWorldEdit ProtocolLib)

**Comment by NetherDragonTw** [comment]
你有連mangodb嗎?
沒有連正常現象

**Comment by NetherDragonTw** [comment]
然後問題是我現在找不到mangodb的連接位
:/
Goodest大大出來救我 我是個編程菜鳥

**Comment by Zhuyuan0907** [comment]
> 你有連mangodb嗎? 沒有連正常現象

完全不關MongoDB的問題
然後 是M"o"ngoDB, not mangoDB

**Comment by endrmen9487** [comment]
> > 你有連mangodb嗎? 沒有連正常現象
> 
> 完全不關MongoDB的問題 然後 是M"o"ngoDB, not mangoDB

那麼該怎麼辦qwq

**Comment by Zhuyuan0907** [comment]
> [新文字文件.txt](https://github.com/RealGoodestEnglish/Eden/files/10049273/default.txt) 我正在使用Feather Client的伺服器功能使用此插件，但是伺服器偵測不到Eden跟其他插件(WorldEdit FastAsyncWorldEdit ProtocolLib)

**********************************************
** This Minecraft version (git-PaperSpigot-445 (MC: 1.8.8)) is not supported by this version of WorldEdit.
** Please download an OLDER version of WorldEdit which does.
**********************************************
這邊說你裝的WorldEdit太新版 不支援1.8.8版本的server
裝舊版的WorldEdit就可以了
但建議裝FastAsyncWorldEdit
https://www.spigotmc.org/resources/fastasyncworldedit.13932/?__cf_chl_tk=RUqDj9EDWP3JlExN3I6HUyMOTQbjxv8kma7x.VFwfTA-1668941318-0-gaNycGzNCdE

把這個放進server 原本的WorldEdit刪掉 應該就可以用了

**Comment by NetherDragonTw** [comment]
> > 你有連mangodb嗎? 沒有連正常現象
> 
> 完全不關MongoDB的問題 然後 是M"o"ngoDB, not mangoDB

抱歉打擾
痾 但是我伺服器這邊也是載入不出來欸
已經打/plugins確認過了
沒有eden的蹤跡
然後抱歉打錯

**Comment by Zhuyuan0907** [comment]
> > > 你有連mangodb嗎? 沒有連正常現象
> > 
> > 完全不關MongoDB的問題 然後 是M"o"ngoDB, not mangoDB
> 
> 抱歉打擾
> 痾 但是我伺服器這邊也是載入不出來欸
> 已經打/plugins確認過了
> 沒有eden的蹤跡
> 然後抱歉打錯

先檢查你用什麼核心 有沒有裝錯
再把需要的附加插件安裝上去
有錯誤再來問

**Comment by NetherDragonTw** [comment]
> > > > 你有連mangodb嗎? 沒有連正常現象
> > > 
> > > 
> > > 完全不關MongoDB的問題 然後 是M"o"ngoDB, not mangoDB
> > 
> > 
> > 抱歉打擾
> > 痾 但是我伺服器這邊也是載入不出來欸
> > 已經打/plugins確認過了
> > 沒有eden的蹤跡
> > 然後抱歉打錯
> 
> 先檢查你用什麼核心 有沒有裝錯 再把需要的附加插件安裝上去 有錯誤再來問

paper 用feather開
然後附加插件是從源代碼copy出來直接丟進去的
但是一樣eden載入不出來
我指的附加插件是FAWE viaversions那些的

**Comment by RealGoodestEnglish** [comment]
> [新文字文件.txt](https://github.com/RealGoodestEnglish/Eden/files/10049273/default.txt) 我正在使用Feather Client的伺服器功能使用此插件，但是伺服器偵測不到Eden跟其他插件(WorldEdit FastAsyncWorldEdit ProtocolLib)

`[17:22:17 ERROR]: Could not load 'plugins\Eden-1.0.11-BETA-3d1abd2-all.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: WorldEdit`
因為上面的WorldEdit 沒有成功加載, 所以才會有這個情況發生
跟留言說的一樣, 你需要一個支援1.8的WorldEdit插件

**Comment by RealGoodestEnglish** [comment]
> 然後問題是我現在找不到mangodb的連接位 :/ Goodest大大出來救我 我是個編程菜鳥

如果問題還沒解決, 請開啟一個新的Issues, 並且在新的Issues裏面告訴我你是使用什麼開啟你的MongoDB
