### ISSUE TITLE
edit kit

### ISSUE THREAD

**Issue by Zhuyuan0907** [RealGoodestEnglish/Eden#17]
當創建一個新KIt時
在更改kit圖示 雙手沒拿東西
然後圖示就換成了air
![image](https://user-images.githubusercontent.com/75146874/204305172-b0a1c14e-7893-4d4c-bb0a-37cd047419c9.png)

換成air之後 第二頁就打不開了
必須要刪除再新增才可以再次打開第二頁
![image](https://user-images.githubusercontent.com/75146874/204305423-07450335-1712-4426-9706-cc28b0882c43.png)
(按下去沒反應 會直接把整個編輯畫面關掉)

意外發現的小bug

**Comment by RealGoodestEnglish** [comment]
已在新版本修復
