### ISSUE TITLE
凍結問題

### ISSUE THREAD

**Issue by Zhuyuan0907** [RealGoodestEnglish/Eden#18]
在Kit中 有一個選項叫做"開始時凍結"
![image](https://user-images.githubusercontent.com/75146874/204308460-7d423eeb-c66a-454c-8da0-c7a839b6f2c8.png)

但在遊戲開始 倒數5秒時
凍結照理來講不能移動
但卻可以丟終界珍珠來進行移動
![image](https://user-images.githubusercontent.com/75146874/204309265-c9e79807-57ea-47bf-bb0a-9e32e917a66a.png)

**Comment by RealGoodestEnglish** [comment]
已在新版本修復
