### ISSUE TITLE
不算是bug 算是不夠

### ISSUE THREAD

**Issue by Zhuyuan0907** [RealGoodestEnglish/Eden#19]
![image](https://user-images.githubusercontent.com/75146874/205321996-a08a7e46-a529-4743-825c-9d0de080155b.png)
kit由於太多 無法將所有模式顯示出來

**Comment by RealGoodestEnglish** [comment]
請嘗試這個版本: https://github.com/RealGoodestEnglish/Eden/releases/tag/1.0.14-BETA-204c77d
