### ISSUE TITLE
Party Problem

### ISSUE THREAD

**Issue by Zhuyuan0907** [RealGoodestEnglish/Eden#8]
![image](https://user-images.githubusercontent.com/75146874/198834892-bd4c1194-58ab-4075-9a2d-bfcb8b71249b.png)
當我們在進行party時
party leader離線
然後party member跳進洞裡 得到分數時
party leader會被傳回去
但看不到任何人
也無法得分

**Comment by RealGoodestEnglish** [comment]
Fixed in https://github.com/RealGoodestEnglish/Eden/releases/tag/1.0.8-BETA-8998982
